/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  MaliciousBidder,
  MaliciousBidderInterface,
} from "../../../contracts/test/MaliciousBidder";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract INounsAuctionHouse",
        name: "auctionHouse",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "bid",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608080604052346100155760eb908161001b8239f35b600080fdfe6080806040526004361015601b575b503615601957600080fd5bfe5b600090813560e01c6359d667a51460315750600e565b604036600319011260b157816004356001600160a01b0381169081900360b157803b1560b15763196774ad60e21b83526024803560048501528391829034905af1801560a657607e575080f35b67ffffffffffffffff811160925760405280f35b634e487b7160e01b82526041600452602482fd5b6040513d84823e3d90fd5b5080fdfea26469706673582212208431b4ac5066f1b0098ccb61a52843d2d1dfe52fb11eda605546feab51a3b2cc64736f6c63430008140033";

type MaliciousBidderConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MaliciousBidderConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MaliciousBidder__factory extends ContractFactory {
  constructor(...args: MaliciousBidderConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<MaliciousBidder> {
    return super.deploy(overrides || {}) as Promise<MaliciousBidder>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MaliciousBidder {
    return super.attach(address) as MaliciousBidder;
  }
  override connect(signer: Signer): MaliciousBidder__factory {
    return super.connect(signer) as MaliciousBidder__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MaliciousBidderInterface {
    return new utils.Interface(_abi) as MaliciousBidderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MaliciousBidder {
    return new Contract(address, _abi, signerOrProvider) as MaliciousBidder;
  }
}
